---
default_stages: [commit, manual]
fail_fast: false
# TODO: Temporary processing for arene-cockpit-misc-actions
# ignore actions directory
exclude: actions

repos:
  - repo: https://github.tmc-stargate.com/arene-os-services-cockpit-wa/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=auto"]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]

  - repo: https://github.tmc-stargate.com/arene-os-services-cockpit-wa/arene-cockpit-misc-pre-commit
    rev: v0.1.0
    hooks:
      - id: infra-cpplint-local
        stages: [commit]

  - repo: https://github.tmc-stargate.com/arene-os-services-cockpit-wa/arene-cockpit-misc-pre-commit
    rev: v0.1.0
    hooks:
      - id: infra-cpplint-ci
        stages: [manual]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: [-s, -d, "{extends: default, rules: {line-length: {max: 120}, truthy: {check-keys: false}}}"]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks/
    rev: 2.1.6
    hooks:
      - id: shellcheck

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.7.4
    hooks:
      - id: pylint

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint
        args: [--config, ".markdownlint.yaml"]
