version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
        - doxygen docs/doxygen/Doxyfile
        - python3 docs/source/generate_module_docs.py docs/doxygen/xml
        - mv modules.rst docs/source

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py