version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    pre_build:
        - cd docs/doxygen && doxygen Doxyfile
        - cd ../source && python3 generate_module_docs.py ../doxygen/xml
        - cd ../..  # Just in case next build step doesn't set working directory

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py