# This is a basic workflow to help you get started with Actions

name: arene-ivi-homescreen_ivi-homescreen

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths-ignore: ".github/workflows/**"
  pull_request:
    branches: [ main ]
    paths-ignore: ".github/workflows/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  github-hook-build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, infra-hook-build ]
    container:
      image: arene-os-services-cockpit-docker.artifactory-ha.tmc-stargate.com/poky-tekton:latest
      options: --user tekton
      credentials:
        username: ${{ secrets.TMCSTARGATE_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.TMCSTARGATE_ARTIFACTORY_PASSWORD }}
      volumes:
        - ${{ github.workspace }}/workdir:/workdir
    env:
      component: ${{ 'arene-ivi' }}
      unit: ${{ 'homescreen' }}
      GITHUB_URL: "https://github.tmc-stargate.com/arene-os-services-cockpit-tmc-wa/"
      TARGET_REPOSITORY: "ivi-homescreen"
      EVENT_TYPE: "github-actions-hook-build"
      CODEQL_DISPATCH_TYPES: "none"
      ENABLE_HOOK_BUILD: "true"
      ADD_UNIT_LABEL: "true"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Initialize setup
        working-directory: ${{ github.workspace }}
        env:
          TMCSTARGATE_GITHUB_USER: ${{ secrets.TMCSTARGATE_GITHUB_USER }}
          TMCSTARGATE_GITHUB_TOKEN: ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e
          # change the owner to be tekton
          sudo chown tekton:tekton /workdir
          sudo chown tekton:tekton -R /github/home
          # Setting ~/.netrc for authentication
          echo "machine github.tmc-stargate.com login ${TMCSTARGATE_GITHUB_USER} password ${TMCSTARGATE_GITHUB_TOKEN}" > /workdir/.netrc
          if [ -e /github/home/.netrc ];then
            rm /github/home/.netrc
          fi
          sudo ln -s /workdir/.netrc /github/home/.netrc
          # Remove the arene-ivi-misc-integ-integrator directory
          if [ -e "/workdir/arene-ivi-misc-integ-integrator" ];then
            rm -rf /workdir/arene-ivi-misc-integ-integrator
          fi
      - name: Checkout repository of arene-ivi-misc-integ-integrator
        uses: actions/checkout@v2
        with:
          repository: arene-os-services-cockpit-tmc-wa/arene-ivi-misc-integ-integrator
          path: workdir/arene-ivi-misc-integ-integrator
          token: ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}
      - name: Branch name of the merge destination
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: merge_branch
      - name: Execute pull_request/merge hook build in Github Actions
        working-directory: ${{ github.workspace }}/workdir
        env:
          BRANCH_PULLREQ_HEAD: ${{ github.event.pull_request.head.ref }}
          BRANCH_MASTER: ${{ steps.merge_branch.outputs.branch }}
          EVENT_NAME: ${{ github.event_name }}
          PULLREQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULLREQUEST_ORG_AND_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        shell: bash
        run: |
          set -e
          #
          # Execute YML of arene-ivi-infra-github-hook-source-code-build and execute hook build by the repository dispatch function.
          # リポジトリディスパッチ機能により、arene-ivi-infra-github-hook-source-code-buildのYMLを実行し、フックビルドを実行する
          #
          function execute_github-actions_hook_build() {
            if [[ ${EVENT_NAME} == "pull_request" ]];then
              TARGET_BRANCH=${BRANCH_PULLREQ_HEAD}
            else
              TARGET_BRANCH=${BRANCH_MASTER}
            fi
            echo "BRANCH_PULLREQ_HEAD: ${BRANCH_PULLREQ_HEAD}"
            echo "BRANCH_MASTER: ${BRANCH_MASTER}"
            echo "EVENT_NAME: ${EVENT_NAME}"
            echo "TARGET_BRANCH : ${TARGET_BRANCH}"
            # Call the build job
            if [[ ${ENABLE_HOOK_BUILD} == "true" ]];then
              curl -n -v \
                  -X POST \
                  -d "{ \"event_type\": \"${EVENT_TYPE}\", \
                    \"client_payload\": { \
                    \"TARGET_REPOSITORY\": \"${TARGET_REPOSITORY}\", \
                    \"TARGET_BRANCH\": \"${TARGET_BRANCH}\", \
                    \"COMPONENT\": \"${component}\", \
                    \"UNIT\": \"${unit}\", \
                    \"PULLREQUEST_NUMBER\": \"${PULLREQUEST_NUMBER}\", \
                    \"PULLREQUEST_ORG_AND_REPO_NAME\": \"${PULLREQUEST_ORG_AND_REPO_NAME}\" \
                    } }" \
                  https://github.tmc-stargate.com/api/v3/repos/arene-os-services-cockpit-wa/arene-ivi-infra-github-hook-source-code-build/dispatches
            fi
          }
          #
          # main
          #
          function main() {
              execute_github-actions_hook_build
          }
          main
      - name: Execute codeql in Github Actions
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ github.workspace }}/workdir
        env:
          BRANCH_PULLREQ_HEAD: ${{ github.event.pull_request.head.ref }}
          PULLREQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULLREQUEST_ORG_AND_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        shell: bash
        run: |
          set -e
          # Call the CodeQL job
          if [[ ${ENABLE_HOOK_BUILD} == "true" && ${CODEQL_DISPATCH_TYPES} != "none" ]];then
            curl -n -v \
                -X POST \
                -d "{ \"event_type\": \"${CODEQL_DISPATCH_TYPES}\", \
                  \"client_payload\": { \
                  \"TARGET_BRANCH\": \"${BRANCH_PULLREQ_HEAD}\", \
                  \"PULLREQUEST_NUMBER\": \"${PULLREQUEST_NUMBER}\", \
                  \"PULLREQUEST_ORG_AND_REPO_NAME\": \"${PULLREQUEST_ORG_AND_REPO_NAME}\" \
                  } }" \
                https://github.tmc-stargate.com/api/v3/repos/arene-os-services-cockpit-wa/arene-ivi-infra-codeql-analysis/dispatches
          fi
      - name: Add unit name label to pull-request-page
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ${{ github.workspace }}/workdir
        env:
          PULLREQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULLREQUEST_ORG_AND_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}
        shell: bash
        run: |
          set -e
          # Add unit name label
          if [[ ${ADD_UNIT_LABEL} == "true" ]];then
            # Add "unit : " to label, because identify other labels.
            ./arene-ivi-misc-integ-integrator/update_pull-req-label.sh POST "unit : ivi-homescreen"
          fi
      - name: Finalize
        if: success() || failure()
        working-directory: ${{ github.workspace }}/workdir
        shell: bash
        run: |
          set -e
          # Remove the checkout repository
          if [ -e "arene-ivi-misc-integ-integrator" ];then
            rm -rf ./arene-ivi-misc-integ-integrator
          fi
