# This is a basic workflow to help you get started with Actions

name: cpplint

# Controls when the workflow will run
on:
  pull_request:
    branches: [ master ]
    paths-ignore: ".github/workflows/**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cpplint-job:
    # The type of runner that the job will run on
    runs-on: [ infra-cpplint ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: arene-os-services-cockpit-tmc-wa/arene-ivi-misc-integ-integrator
          path: arene-ivi-misc-integ-integrator
          token: ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}
      - name: Exec cpplint 
        uses: ./arene-ivi-misc-integ-integrator/actions/cpplint/
