
 name: pull-request-check

 on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

 jobs:
  merge_permission_judge:
    runs-on: [ self-hosted, infra-hook-build ]
    steps:
    - name: Merge Enabled
      id: merge_enabled
      if: |
        ((github.event.action == 'labeled') &&
         (github.event.label.name == 'hook-job-succeeded')) ||
        contains(github.event.pull_request.labels.*.name, 'hook-job-succeeded')
      run: |
        #!/bin/bash
        echo "Result of merege judge : Enabled"
    - name: Merge Disabled
      id: merge_disabled
      if: steps.merge_enabled.conclusion == 'skipped'
      run: |
        #!/bin/bash
        echo "Result of merege judge : Disabled"
        exit 1
