---
name: pre-commit

on:
  pull_request:
    branches: [ master ]

jobs:
  pre-commit:
    runs-on: [self-hosted, infra-pre-commit]
    container:
      image: arene-os-services-cockpit-docker.artifactory-ha.tmc-stargate.com/cockpit-generic:latest
      options: --user cockpit-user
      credentials:
        username: ${{ secrets.TMCSTARGATE_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.TMCSTARGATE_ARTIFACTORY_PASSWORD }}
      volumes:
        - ${{ github.workspace }}/workdir:/workdir

    steps:
      - name: Initialize_setup
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          set -e
          # change the owner to be cockpit-user
          sudo chown cockpit-user:cockpit-user /workdir
          sudo chown cockpit-user:cockpit-user -R /github/home
          # workspace reflesh
          if [ -d /workdir ] ; then
            echo "Delete /workdir/*"
            rm -rf /workdir/*
          fi

      - name: Git_clone_arene-cockpit-misc-actions
        uses: actions/checkout@v2
        with:
          repository: arene-os-services-cockpit-wa/arene-cockpit-misc-actions
          path: workdir/arene-cockpit-misc-actions
          token: ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}
          set-safe-directory: false

      - name: setup netrc
        uses: ./workdir/arene-cockpit-misc-actions/actions/setup_netrc
        with:
          stargate_github_user: ${{ secrets.TMCSTARGATE_GITHUB_USER }}
          stargate_github_token: ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}
          stargate_artifactory_username: ${{ secrets.TMCSTARGATE_ARTIFACTORY_USERNAME }}
          stargate_artifactory_password: ${{ secrets.TMCSTARGATE_ARTIFACTORY_PASSWORD }}

      - name: Git_clone_pre-commit_target
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          path: workdir/pre-commit_target
          set-safe-directory: false

      - name: Run pre-commit
        working-directory: ${{ github.workspace }}/workdir
        env:
          TARGET_DIR: pre-commit_target
        shell: bash
        run: |
          cd ${TARGET_DIR}
          pre-commit clean
          pre-commit install
          pre-commit run -a --hook-stage manual
