---
name: pre-commit

on:
  pull_request:
    branches: "master"
    branches-ignore: "sync/**"

jobs:
  pre-commit:
    runs-on: [self-hosted, infra-pre-commit]
    container:
      image: arene-os-services-cockpit-docker.artifactory-ha.tmc-stargate.com/cockpit-generic:latest
      options: --user cockpit-user
      credentials:
        username: ${{ secrets.TMCSTARGATE_ARTIFACTORY_USERNAME }}
        password: ${{ secrets.TMCSTARGATE_ARTIFACTORY_PASSWORD }}
      volumes:
        - ${{ github.workspace }}/workdir:/workdir

    steps:
      - name: Initialize_setup
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          set -e
          # change the owner to be cockpit-user
          sudo chown cockpit-user:cockpit-user /workdir
          sudo chown cockpit-user:cockpit-user -R /github/home
          # workspace reflesh
          if [ -d /workdir ] ; then
            echo "Delete /workdir/*"
            rm -rf /workdir/*
          fi
          # setup netrc
          echo "machine github.tmc-stargate.com" > ~/.netrc
          echo "login ${{ secrets.TMCSTARGATE_GITHUB_USER }}" >> ~/.netrc
          echo "password ${{ secrets.TMCSTARGATE_GITHUB_TOKEN }}" >> ~/.netrc
          chmod go-rw ~/.netrc

      - name: git clone pre-commit target
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          path: workdir/pre-commit-target
          set-safe-directory: false

      - name: Run pre-commit
        working-directory: ${{ github.workspace }}/workdir
        env:
          TARGET_DIR: pre-commit-target
        shell: bash
        run: |
          cd ${TARGET_DIR}
          pre-commit clean
          pre-commit install
          pre-commit run -a --hook-stage manual
